name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set date variable
      id: date
      run: echo "::set-output name=date::$(date +%s)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/majlitech/simplecctv:${{ steps.date.outputs.date }}
    - name: Push to registry
      run: docker push ghcr.io/majlitech/simplecctv:${{ steps.date.outputs.date }}
